# Ansible role to deploy nginx load-balancer 

---

- name: Install haproxy
  yum:
    name: haproxy

    
- name: Configure the lb upstream servers
  template: src=haproxy-flask.conf dest=/etc/haproxy/haproxy.cfg


- name: Start haproxy
  systemd:
    name: haproxy
    state: restarted